config/routes.rb
Rails.application.routes.draw do
  get "/register/:role", to: "users#new", as: "register"
  post "/register/:role", to: "users#create", as: "register_post"

  get "/login", to: "user_sessions#new", as: "login"
  post "/login", to: "user_sessions#create", as: "login_post"
  delete "/logout", to: "user_sessions#destroy", as: "logout"

  scope "/app" do
    resources :restaurants do
      resources :menus, shallow: true
    end

    resources :orders, only: [:index, :show, :create, :update, :destroy]

    resources :users, only: [:index, :show, :edit, :update, :destroy]

    get "/profile", to: "dashboard#profile", as: "profile"
  end
  get "/app", to: "restaurants#index", as: "dashboard"

  root "static_pages#landing"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_login, only: [:index]

  def index
  end

  def profile
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def cp(path)
    "current" if current_page?(path)
  end
end

app/views/dashboard/_header.html.erb
<header id="header" class="page-topbar">
  <!-- start header nav-->
  <div class="navbar-fixed">
    <nav class="navbar-color grey darken-4">
      <div class="nav-wrapper">
        <ul class="left">
          <li>
            <h1 class="logo-wrapper">
              <a href="<%= %>" class="brand-logo darken-1">
                <%= image_tag  "logo-white.svg", "alt-text": "go feed logo", class: "white-text" %>
                <span class="logo-text heading logo-font">GO-FEED</span>
              </a>
            </h1>
          </li>
        </ul>
        <ul class="right hide-on-med-and-down">
          <li>
            <a href="javascript:void(0);" class="waves-effect waves-block waves-light notification-button" data-activates="notifications-dropdown">
              <i class="material-icons">notifications_none
              </i>
            </a>
            <ul id="notifications-dropdown" class="dropdown-content">
              <li>
                <h6>NOTIFICATIONS
                  <!-- <span class="new badge">5</span> -->
                </h6>
              </li>
              <li class="divider"></li>
              <li>
                <a href="#!" class="grey-text text-darken-2">
                  <small>You have no unread notifications :)</small>
                </a>
              </li>
            </ul>
          </li>
          <li>
            <a href="<%= profile_path %>" class="waves-effect waves-block waves-light profile-button" title="Profile">
              <span class="avatar-status avatar-online">
                <%= image_tag "no-user.png" %>
                <i></i>
              </span>
              <span style="margin-left: 1rem">
                Welcome, <%= current_user.username %>
              </span>
            </a>
          </li>
          <li>
            <a href="<%= logout_path %>" class="waves-effect waves-block waves-light profile-button" title="Logout" id="logout" data-method="delete" rel="nofollow">
              <span class="">
                <i class="material-icons">exit_to_app</i>
              </span>
            </a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
  <!-- end header nav-->
</header>

app/views/dashboard/_sidebar.html.erb
<aside id="left-sidebar-nav">
  <ul id="slide-out" class="side-nav fixed leftside-navigation ps-container ps-active-y" style="transform: translateX(0%);">
    <li class="no-padding">
      <ul class="collapsible expandable" data-collapsible="accordion">
        <li class="bold">
          <a href="<%= restaurants_path %>" class="waves-effect red darken-2 white-text">
            <i class="fa fa-plus white-text"></i>
            <span class="nav-text">Order Food</span>
          </a>
        </li>
        <li class="bold">
          <a href="<%= restaurants_path %>" class="waves-effect white red-text text-darken-2 <%= cp(restaurants_path) %>">
            <i class="material-icons red-text text-darken-2">restaurant_menu</i>
            <span class="nav-text">Restaurants</span>
          </a>
        </li>
        <li class="bold">
          <a href="<%= orders_path %>" class="waves-effect white red-text text-darken-2 <%= cp(orders_path) %>">
            <i class="fa fa-file-invoice red-text text-darken-2"></i>
            <span class="nav-text">Orders</span>
          </a>
        </li>
        <% if current_user.admin? %>
          <li class="bold">
            <a href="<%= users_path %>" class="waves-effect white red-text text-darken-2 <%= cp(users_path) %>">
              <i class="fa fa-users red-text text-darken-2"></i>
              <span class="nav-text">Users</span>
            </a>
          </li>
        <% end %>
      </ul>
    </li>
  </ul>
  <a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only red darken-2">
    <i class="material-icons">menu</i>
  </a>
</aside>

app/views/dashboard/index.html.erb
<% content_for :dashboard_title do %>
<% end %>

<% content_for :dashboard_header do %>
  <%= render 'header' %>
<% end %>

<% content_for :dashboard_sidebar do %>
  <%= render 'sidebar' %>
<% end %>

<% content_for :dashboard_content do %>
  <section id="content">
    <!--start container-->
    <div class="container">
    </div>
    <!--end container-->
  </section>
<% end %>

app/views/dashboard/profile.html.erb
<% content_for :dashboard_title do %>
<% end %>

<% content_for :dashboard_header do %>
  <%= render 'header' %>
<% end %>

<% content_for :dashboard_sidebar do %>
  <%= render 'sidebar' %>
<% end %>

<% content_for :dashboard_content do %>
  <section id="content">
    <!--start container-->
    <div class="container">
      <h3>PROFILE</h3>
    </div>
    <!--end container-->
  </section>
<% end %>