config/routes.rb
Rails.application.routes.draw do
  get "/register/:role", to: "users#new", as: "register"
  post "/register/:role", to: "users#create", as: "register_post"

  get "/login", to: "user_sessions#new", as: "login"
  post "/login", to: "user_sessions#create", as: "login_post"
  delete "/logout", to: "user_sessions#destroy", as: "logout"

  scope "/app" do
    resources :restaurants do
      resources :menus, shallow: true
    end

    resources :orders, only: [:index, :show, :create, :update, :destroy]

    resources :users, only: [:index, :show, :edit, :update, :destroy]

    get "/profile", to: "dashboard#profile", as: "profile"
  end
  get "/app", to: "restaurants#index", as: "dashboard"

  root "static_pages#landing"
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:admin, :customer, :driver]
  validates :role, inclusion: { in: roles.keys }

  acts_as_authentic

  def admin?
    self.role == "admin"
  end

  def customer?
    self.role == "customer"
  end

  def driver?
    self.role == "driver"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :require_logout, only: [:new, :create]
  before_action :require_admin, only: [:index]

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
    @role = params[:role]
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_user
      @user = User.find(params[:id])
      require_admin if @user != current_user
    end

    def user_params
      params.require(:user).permit(:username, :email, :role, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, url: register_post_path(role), local: true) do |f| %>
  <div class="input-field">
    <%= f.label :username %>
    <%= f.text_field :username %>
    <% if user.errors[:username].any? %>
      <small class="red-text"><%= user.errors.full_messages_for(:username).first %></small>
    <% end %>
  </div>

  <div class="input-field">
    <%= f.label :email %>
    <%= f.text_field :email %>
    <% if user.errors[:email].any? %>
      <small class="red-text"><%= user.errors.full_messages_for(:email).first %></small>
    <% end %>
  </div>

  <div class="input-field">
    <%= f.hidden_field :role, value: role %>
  </div>
  <div class="input-field">
    <%= f.label :password %>
    <%= f.password_field :password %>
    <% if user.errors[:password].any? %>
      <small class="red-text"><%= user.errors.full_messages_for(:password).first %></small>
    <% end %>
  </div>

  <div class="input-field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <% if user.errors[:password_confirmation].any? %>
      <small class="red-text"><%= user.errors.full_messages_for(:password_confirmation).first %></small>
    <% end %>
  </div>

  <div class="actions">
    <%= f.button "Register", type: :submit, class: "btn waves-effect waves-light red darken-2 white-text" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render partial: 'form', locals: { user: @user, role: @user.role } %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
    <th>Username</th>
    <th>Email</th>
    <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<% content_for :title do %>
  Register
<% end %>

<div class="register-content">
  <div class="register-container card hoverable">
    <div class="register-heading">
      <h2 class="register-heading-logo red-text text-darken-2">
        <i class="fa fa-utensils"></i>GO-FEED
      </h2>
      <h4 class="register-heading-title">sign up as <%= @role %></h4>
    </div>
    <div class="register-form">
      <%= render partial: 'form', locals: { user: @user, role: @role } %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <strong>Username:</strong>
    <%= @user.username %>
</p>

<p>
    <strong>Email:</strong>
    <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>