config/routes.rb
Rails.application.routes.draw do
  get "/register/:role", to: "users#new", as: "register"
  post "/register/:role", to: "users#create", as: "register_post"

  get "/login", to: "user_sessions#new", as: "login"
  post "/login", to: "user_sessions#create", as: "login_post"
  delete "/logout", to: "user_sessions#destroy", as: "logout"

  scope "/app" do
    resources :restaurants do
      resources :menus, shallow: true
    end

    resources :orders, only: [:index, :show, :create, :update, :destroy]

    resources :users, only: [:index, :show, :edit, :update, :destroy]

    get "/profile", to: "dashboard#profile", as: "profile"
  end
  get "/app", to: "restaurants#index", as: "dashboard"

  root "static_pages#landing"
end

app/models/restaurant.rb
require "http"
require "json"

class Restaurant < ApplicationRecord
  validates :name, :address, presence: true

  belongs_to :position

  has_many :menus

  def fetch_staticmap
    params = { origin: self.position.to_s }

    url = "#{ENV["GATEWAY_URI"]}/staticmap?#{params.to_query}"
    resp = HTTP.get(url)
    json = JSON.parse(resp.to_s)
    json["staticmap"]
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :require_admin, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @staticmap = @restaurant.fetch_staticmap
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    position = Position.create(filtered_params.slice(:latitude, :longitude))
    @restaurant = Restaurant.new(restaurant_params.merge(position: position))

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    position = Position.new(filtered_params.slice(:latitude, :longitude))
    restaurant_params = restaurant_params.merge(position: position) if position.save

    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def filtered_params
      params.require(:restaurant).permit(:name, :address, :description, :phone, :latitude, :longitude)
    end

    def restaurant_params
      filtered_params.slice(:name, :address, :description, :phone)
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.number_field :latitude, step: :any %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.number_field :longitude, step: :any %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<% content_for :dashboard_title do %>
  Restaurants
<% end %>

<% content_for :dashboard_header do %>
  <%= render 'dashboard/header' %>
<% end %>

<% content_for :dashboard_sidebar do %>
  <%= render 'dashboard/sidebar' %>
<% end %>

<% content_for :dashboard_content do %>
  <section id="content">
    <!--start container-->
    <div class="container">
      <p id="notice"><%= notice %></p>

      <% @restaurants.each do |restaurant| %>
        <div class="row">
          <div class="col s12">
            <div class="card-panel hoverable waves-effect" style="width: 100%" onclick="location.href='<%= restaurant_path(restaurant) %>'">
              <h3><%= restaurant.name %></h3>
              <p><%= restaurant.address %></p>
              <p><%= restaurant.description %></p>
              <small><%= restaurant.phone %></small>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <!--end container-->
  </section>
<% end %>

<%= render template: "layouts/dashboard" %>

<%= link_to 'New Restaurant', new_restaurant_path if current_user.admin? %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<% content_for :dashboard_title do %>
  Order from <%= @restaurant.name %>
<% end %>

<% content_for :dashboard_header do %>
  <%= render 'dashboard/header' %>
<% end %>

<% content_for :dashboard_sidebar do %>
  <%= render 'dashboard/sidebar' %>
<% end %>


<% content_for :dashboard_content do %>
  <section id="content">
    <!--start container-->
    <div class="container">
      <div class="card-panel">
        <div class="row">
          <div class="col s12 m6">
            <h4><%= @restaurant.name %></h4>
            <p><%= @restaurant.address %> &bull; <%= @restaurant.phone ? @restaurant.phone : '-' %></p>
            <p><%= @restaurant.description %></p>
            <% if current_user.admin? %>
              <%= link_to 'Edit', edit_restaurant_path(@restaurant), class: "btn white red-text text-darken-2" %>
              <%= link_to 'Delete', @restaurant, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn white red-text text-darken-2" %>
            <% end %>
          </div>
          <div class="col s12 m6">
            <img src="data:image/jpg;base64, <%= @staticmap %>" />
          </div>
        </div>
        <div class="row">
        </div>
      </div>
      <%= render partial: 'orders/form', locals: { order: Order.new, restaurant: @restaurant } %>
    </div>
    <!--end container-->
  </section>
<% end %>

<%= render template: 'layouts/dashboard' %>